// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirpy.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChirpy = `-- name: CreateChirpy :one

INSERT INTO chirpy (id,createdAt,updatedAt,body,userId)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, createdat, updatedat, body, userid
`

type CreateChirpyParams struct {
	Body   string
	Userid uuid.UUID
}

func (q *Queries) CreateChirpy(ctx context.Context, arg CreateChirpyParams) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, createChirpy, arg.Body, arg.Userid)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Body,
		&i.Userid,
	)
	return i, err
}

const fetchChirps = `-- name: FetchChirps :many
SELECT id, createdat, updatedat, body, userid FROM chirpy ORDER BY createdAt
`

func (q *Queries) FetchChirps(ctx context.Context) ([]Chirpy, error) {
	rows, err := q.db.QueryContext(ctx, fetchChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirpy
	for rows.Next() {
		var i Chirpy
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.Updatedat,
			&i.Body,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
