// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Chirpy struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Body      string
	Userid    uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Email     string
}
