// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id,createdAt,updatedAt,email,password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, createdat, updatedat, email, password
`

type CreateUserParams struct {
	Email    string
	Password sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const fetchUserByEmail = `-- name: FetchUserByEmail :one
SELECT id, createdat, updatedat, email, password FROM users where email = $1
`

func (q *Queries) FetchUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, fetchUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const fetchUserWithoutPassword = `-- name: FetchUserWithoutPassword :one
SELECT id,email,createdAt,updatedAt FROM users where email = $1
`

type FetchUserWithoutPasswordRow struct {
	ID        uuid.UUID
	Email     string
	Createdat time.Time
	Updatedat time.Time
}

func (q *Queries) FetchUserWithoutPassword(ctx context.Context, email string) (FetchUserWithoutPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, fetchUserWithoutPassword, email)
	var i FetchUserWithoutPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
